apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  type: NodePort  # Local testing friendly; maps cluster port to your local machine
  selector:
    app: heart-disease-ml
  ports:
    - protocol: TCP
      port: 8000       # Internal Cluster Port
      targetPort: 8000 # App Port inside the container
      nodePort: 30080  # Accessible at http://localhost:30080